### ISSUE TITLE
Invalid bin entry for "atomico/library"

### ISSUE THREAD

**Issue by efoken** [atomicojs/vite#2]
We keep getting warnings with Yarn v1 in our CI:

```
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
warning @atomico/vite@2.20.0: Invalid bin entry for "atomico/library" (in "@atomico/vite").
[3/4] Linking dependencies...
```

Even worse: This warning turns into an error using Yarn v2 and newer. Because of this package we cannot update to newer Yarn versions

**Comment by UpperCod** [comment]
Hi @efoken ,Thank you for your issue. I have fixed this by changing the name of the CLI to avoid conflicts caused by the use of `/`. The two available CLIs are now:
1. `library`
2. `atomico-library`
Please let me know if the conflict with Yarn persists. Best regards.

**Comment by efoken** [comment]
Thanks, works perfect now with Yarn 4 🙏
